name:                l-system
version:             0.1.0.0
github:              "i1i1/lsystem"
license:             BSD3
author:              "i1i1"
maintainer:          "vanyarybin1@live.ru"
copyright:           "2021 i1i1"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lsystem#readme>

dependencies:
- base >= 4.7 && < 5
- text
- svg-builder

library:
  source-dirs: src

tests:
  l-system-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l-system
